; This is an .INI file, used as a simple way to tune a game without recompiling/hardcoding it.
; A great place for gameplay variables and more. Another example of data-driven programming. 
[Level1]
levelFile=../Levels/GameLevel.json
modelPath=../Models
timeLimit=240
[Player]
model=Moni
hitpoints=1
speed=16.0
hubSpeedMult=3.0
firerate=0.4
invulnPeriod=3
lives=2
lifeCap=4
death=DeadPlayer
[Audio]
masterVolume=0.05f
hubMusicVolume=0.8f
subMusicVolume=0.8f
[Life]
model=MoniLife
[Shaders]
pixel=../Shaders/LevelPixel.hlsl
vertex=../Shaders/LevelVertex.hlsl
uiPixel=../Shaders/UIPixelShader.hlsl
uiVertex=../Shaders/UIVertexShader.hlsl
skyboxVertex=../Shaders/SkyboxVertex.hlsl
skyboxPixel=../Shaders/SkyboxPixel.hlsl
[Window]
height=768
width=1024
xstart=100
ystart=100
[Camera]
zoomSpeed=2.0f
[Enemy1]
model=HaywireBot
initialShatterCount=4
hitpoints=1
speed=6.0
shatterAmount=2
shatterScale=0.7
sightRadius=12.5
roamCooldown=2.0f
roamRadius=7.0f
death=DeadBot1
[InvulEnemy]
model=Enforcer
hitpoints=1
speed=8.0
shatterAmount=2
shatterScale=0.7
sightRadius=35.0f
roamCooldown=1.0f
roamRadius=15.0f
[DeadPlayer]
model=DeadMoni
[DeadBot1]
model=BrokenBot
[Bullet]
model=RegBullet
speed=40.0
[Treasure1]
model=Battery
ID=1
Name=Battery
[Treasure2]
model=FloppyDisk
ID=2
Name=Floppy Disk
[Treasure3]
model=CPU
ID=3
Name=CPU
[Treasure4]
model=USBDrive
ID=4
Name=USB Drive
[Treasure5]
model=Monitor
ID=5
Name=Monitor
[Treasure6]
model=Gear
ID=6
Name=Gear
[Treasure7]
model=Fan
ID=7
Name=Cooling Fan
[Treasure8]
model=SDCard
ID=8
Name=SD Card
[Treasure9]
model=Disc
ID=9
Name=Disc
[Treasure10]
model=Chip
ID=10
Name=Chip
[BreakableWall]
model=BreakableWall
[HubWorld1]
TreasureCount=3
Treasure1=Treasure1
Treasure2=Treasure2
Treasure3=Treasure3
PlayerSpawnX=47.0942
PlayerSpawnY=1.75
PlayerSpawnZ=10.5481
SubWorldCount=3
SubWorld1=SubWorld1
SubWorld2=SubWorld2
SubWorld3=SubWorld3
EnemySpawnCount=3
EnemySpawn1=InvulEnemy
EnemySpawnLocationX1=4.73232
EnemySpawnLocationY1=1.75
EnemySpawnLocationZ1=-42.763
EnemySpawn2=InvulEnemy
EnemySpawnLocationX2=-48.4221
EnemySpawnLocationY2=1.75
EnemySpawnLocationZ2=12.357
EnemySpawn3=InvulEnemy
EnemySpawnLocationX3=62.1106
EnemySpawnLocationY3=1.75
EnemySpawnLocationZ3=-8.00957
LifeCount=1
LifeX1=-8.5655
LifeY1=1.75
LifeZ1=-43.056
[SubWorld1]
Treasure=Treasure1
TreasureSpawnLocationX=61.052
TreasureSpawnLocationY=1.75
TreasureSpawnLocationZ=-60.3905
BreakableWallCount=0
EnemySpawnCount=3
EnemySpawn1=Enemy1
EnemySpawnLocationX1=28.8621
EnemySpawnLocationY1=1.75
EnemySpawnLocationZ1=-57.4218
EnemySpawn2=Enemy1
EnemySpawnLocationX2=36.9199
EnemySpawnLocationY2=1.75
EnemySpawnLocationZ2=-52.1217
EnemySpawn3=Enemy1
EnemySpawnLocationX3=61.2279
EnemySpawnLocationY3=1.75
EnemySpawnLocationZ3=-24
model=subWorld1Cover
InvulEnemySpawnTimer=7.0f
InvulEnemySpawnPositions=3
InvulSpawnLocationX1=72.6656
InvulSpawnLocationY1=1.75
InvulSpawnLocationZ1=-61.9763
InvulSpawnLocationX2=9.52498
InvulSpawnLocationY2=1.75
InvulSpawnLocationZ2=-64.3611
InvulSpawnLocationX3=8.69424
InvulSpawnLocationY3=1.75
InvulSpawnLocationZ3=-22.4472
[SubWorld2]
Treasure=Treasure2
TreasureSpawnLocationX=0.524565
TreasureSpawnLocationY=1.75
TreasureSpawnLocationZ=63.5681
BreakableWallCount=4
BreakableWallLocationX1=-4.9
BreakableWallLocationY1=1.75
BreakableWallLocationZ1=46
BreakableWallLocationX2=4.9
BreakableWallLocationY2=1.75
BreakableWallLocationZ2=46
BreakableWallLocationX3=4.9
BreakableWallLocationY3=1.75
BreakableWallLocationZ3=50
BreakableWallLocationX4=-4.9
BreakableWallLocationY4=1.75
BreakableWallLocationZ4=50
EnemySpawnCount=2
EnemySpawn1=Enemy1
EnemySpawnLocationX1=-11.5
EnemySpawnLocationY1=1.75
EnemySpawnLocationZ1=33.2
EnemySpawn2=Enemy1
EnemySpawnLocationX2=11.5
EnemySpawnLocationY2=1.75
EnemySpawnLocationZ2=33.2
model=subWorld2Cover
InvulEnemySpawnTimer=7.0f
InvulEnemySpawnPositions=2
InvulSpawnLocationX1=33.1403
InvulSpawnLocationY1=1.75
InvulSpawnLocationZ1=16.6555
InvulSpawnLocationX2=-32.4543
InvulSpawnLocationY2=1.75
InvulSpawnLocationZ2=16.6555
[SubWorld3]
Treasure=Treasure3
TreasureSpawnLocationX=-39.4072
TreasureSpawnLocationY=1.75
TreasureSpawnLocationZ=-61.7175
BreakableWallCount=0
EnemySpawnCount=6
EnemySpawn1=Enemy1
EnemySpawnLocationX1=-15.3352
EnemySpawnLocationY1=1.75
EnemySpawnLocationZ1=-67.2746
EnemySpawn2=Enemy1
EnemySpawnLocationX2=-16.0587
EnemySpawnLocationY2=1.75
EnemySpawnLocationZ2=-18.8097
EnemySpawn3=Enemy1
EnemySpawnLocationX3=-63.4505
EnemySpawnLocationY3=1.75
EnemySpawnLocationZ3=-18.1739
EnemySpawn4=Enemy1
EnemySpawnLocationX4=-64.5025
EnemySpawnLocationY4=1.75
EnemySpawnLocationZ4=-66.577
EnemySpawn5=Enemy1
EnemySpawnLocationX5=-59.1551
EnemySpawnLocationY5=1.75
EnemySpawnLocationZ5=-44.3733
EnemySpawn6=Enemy1
EnemySpawnLocationX6=-20.4028
EnemySpawnLocationY6=1.75
EnemySpawnLocationZ6=-44.3733
model=SubWorld3Cover
InvulEnemySpawnTimer=7.0f
InvulEnemySpawnPositions=3
InvulSpawnLocationX1=-69.5434
InvulSpawnLocationY1=1.75
InvulSpawnLocationZ1=-43.7656
InvulSpawnLocationX2=-39.3103
InvulSpawnLocationY2=1.75
InvulSpawnLocationZ2=-71.8165
InvulSpawnLocationX3=-9.42369
InvulSpawnLocationY3=1.75
InvulSpawnLocationZ3=-44.3908
; If you change this file it will replace the saved.ini version if its newer. 

;Second Hub World Stuff
[HubWorld2]
TreasureCount=3
Treasure1=Treasure4
Treasure2=Treasure5
Treasure3=Treasure6
PlayerSpawnX=275.3
PlayerSpawnY=1.75
PlayerSpawnZ=-49
SubWorldCount=3
SubWorld1=SubWorld4
SubWorld2=SubWorld5
SubWorld3=SubWorld6
EnemySpawnCount=7
EnemySpawn1=InvulEnemy
EnemySpawnLocationX1=275.31
EnemySpawnLocationY1=1.75
EnemySpawnLocationZ1=-70.34
EnemySpawn2=InvulEnemy
EnemySpawnLocationX2=292.072
EnemySpawnLocationY2=1.75
EnemySpawnLocationZ2=70.7692
EnemySpawn3=InvulEnemy
EnemySpawnLocationX3=258.364
EnemySpawnLocationY3=1.75
EnemySpawnLocationZ3=70.7692
EnemySpawn4=InvulEnemy
EnemySpawnLocationX4=304.926
EnemySpawnLocationY4=1.75
EnemySpawnLocationZ4=18.272
EnemySpawn5=InvulEnemy
EnemySpawnLocationX5=205.42
EnemySpawnLocationY5=1.75
EnemySpawnLocationZ5=40
EnemySpawn6=InvulEnemy
EnemySpawnLocationX6=345.37
EnemySpawnLocationY6=1.75
EnemySpawnLocationZ6=40
EnemySpawn7=InvulEnemy
EnemySpawnLocationX7=245.661
EnemySpawnLocationY7=1.75
EnemySpawnLocationZ7=18.272
LifeCount=2
LifeX1=274.464
LifeY1=1.75
LifeZ1=69.5644
LifeX2=274.464
LifeY2=1.75
LifeZ2=-70.1
[SubWorld4]
Treasure=Treasure4
TreasureSpawnLocationX=275.28
TreasureSpawnLocationY=1.75
TreasureSpawnLocationZ=2.53
BreakableWallCount=2
BreakableWallLocationX1=265.85
BreakableWallLocationY1=1.75
BreakableWallLocationZ1=-1.63
BreakableWallLocationX2=283.85
BreakableWallLocationY2=1.75
BreakableWallLocationZ2=-1.63
EnemySpawnCount=4
EnemySpawn1=Enemy1
EnemySpawnLocationX1=292.259
EnemySpawnLocationY1=1.75
EnemySpawnLocationZ1=-16.8574
EnemySpawn2=Enemy1
EnemySpawnLocationX2=258.86
EnemySpawnLocationY2=1.75
EnemySpawnLocationZ2=-16.8574
EnemySpawn3=Enemy1
EnemySpawnLocationX3=258.86
EnemySpawnLocationY3=1.75
EnemySpawnLocationZ3=16.8574
EnemySpawn4=Enemy1
EnemySpawnLocationX4=292.259
EnemySpawnLocationY4=1.75
EnemySpawnLocationZ4=16.8574
model=subWorld4Cover
InvulEnemySpawnTimer=10.0f
InvulEnemySpawnPositions=4
InvulSpawnLocationX1=249.1
InvulSpawnLocationY1=1.75
InvulSpawnLocationZ1=26.0427
InvulSpawnLocationX2=302.33
InvulSpawnLocationY2=1.75
InvulSpawnLocationZ2=26.0427
InvulSpawnLocationX3=249.1
InvulSpawnLocationY3=1.75
InvulSpawnLocationZ3=-26.0427
InvulSpawnLocationX4=302.33
InvulSpawnLocationY4=1.75
InvulSpawnLocationZ4=-26.0427
[SubWorld5]
Treasure=Treasure5
TreasureSpawnLocationX=234.154
TreasureSpawnLocationY=1.75
TreasureSpawnLocationZ=4.27486
BreakableWallCount=0
EnemySpawnCount=2
EnemySpawn1=Enemy1
EnemySpawnLocationX1=209.776
EnemySpawnLocationY1=1.75
EnemySpawnLocationZ1=0
EnemySpawn2=Enemy1
EnemySpawnLocationX2=234.154
EnemySpawnLocationY2=1.75
EnemySpawnLocationZ2=0
model=subWorld5Cover
InvulEnemySpawnTimer=7.0f
InvulEnemySpawnPositions=2
InvulSpawnLocationX1=234.154
InvulSpawnLocationY1=1.75
InvulSpawnLocationZ1=-12.349
InvulSpawnLocationX2=196.949
InvulSpawnLocationY2=1.75
InvulSpawnLocationZ2=24.9487
[SubWorld6]
Treasure=Treasure6
TreasureSpawnLocationX=330.5
TreasureSpawnLocationY=1.75
TreasureSpawnLocationZ=2.6
BreakableWallCount=2
BreakableWallLocationX1=316.547
BreakableWallLocationY1=1.75
BreakableWallLocationZ1=8.36846
BreakableWallLocationX2=343.54
BreakableWallLocationY2=1.75
BreakableWallLocationZ2=-4.631
EnemySpawnCount=2
EnemySpawn1=Enemy1
EnemySpawnLocationX1=343.5
EnemySpawnLocationY1=1.75
EnemySpawnLocationZ1=15.6
EnemySpawn2=Enemy1
EnemySpawnLocationX2=343.5
EnemySpawnLocationY2=1.75
EnemySpawnLocationZ2=-13.4
model=subWorld6Cover
InvulEnemySpawnTimer=7.0f
InvulEnemySpawnPositions=2
InvulSpawnLocationX1=315.41
InvulSpawnLocationY1=1.75
InvulSpawnLocationZ1=-12.349
InvulSpawnLocationX2=356.89
InvulSpawnLocationY2=1.75
InvulSpawnLocationZ2=24.9487

